//<auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

namespace TheBedstand.Data.Migrations
{
    public partial class AddedSeparateUrlFieldForEntities : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "ImageId",
                table: "Genres",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "CoverId",
                table: "Books",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ImageId",
                table: "Authors",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AvatarUrl",
                table: "AspNetUsers",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ImageId",
                table: "Genres");

            migrationBuilder.DropColumn(
                name: "CoverId",
                table: "Books");

            migrationBuilder.DropColumn(
                name: "ImageId",
                table: "Authors");

            migrationBuilder.DropColumn(
                name: "AvatarUrl",
                table: "AspNetUsers");
        }
    }
}
